{
	"childItems": [{
		"childItems": [{
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.ByThreePoints",
				"itemType": "creation",
				"text": "ByThreePoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.ByCenterPointRadiusAngle",
				"itemType": "creation",
				"text": "ByCenterPointRadiusAngle"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.ByCenterPointStartPointSweepAngle",
				"itemType": "creation",
				"text": "ByCenterPointStartPointSweepAngle"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.ByCenterPointStartPointEndPoint",
				"itemType": "creation",
				"text": "ByCenterPointStartPointEndPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.ByFillet",
				"itemType": "creation",
				"text": "ByFillet"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.ByFilletTangentToCurve",
				"itemType": "creation",
				"text": "ByFilletTangentToCurve"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.ByBestFitThroughPoints",
				"itemType": "creation",
				"text": "ByBestFitThroughPoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.ByStartEndAndTangencies",
				"itemType": "action",
				"text": "ByStartEndAndTangencies"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.ByStartPointEndPointStartTangent",
				"itemType": "creation",
				"text": "ByStartPointEndPointStartTangent"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.CenterPoint",
				"itemType": "query",
				"text": "CenterPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.Radius",
				"itemType": "query",
				"text": "Radius"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.StartAngle",
				"itemType": "query",
				"text": "StartAngle"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Arc.SweepAngle",
				"itemType": "query",
				"text": "SweepAngle"
			}],
			"iconName": "Arc",
			"itemType": "none",
			"text": "Arc"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ByParameterLineOnSurface",
				"itemType": "creation",
				"text": "ByParameterLineOnSurface"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ByBlendBetweenCurves",
				"itemType": "creation",
				"text": "ByBlendBetweenCurves"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ByIsoCurveOnSurface",
				"itemType": "creation",
				"text": "ByIsoCurveOnSurface"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.Length",
				"itemType": "query",
				"text": "Length"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.IsPlanar",
				"itemType": "query",
				"text": "IsPlanar"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.IsClosed",
				"itemType": "query",
				"text": "IsClosed"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.StartPoint",
				"itemType": "query",
				"text": "StartPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.EndPoint",
				"itemType": "query",
				"text": "EndPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.Normal",
				"itemType": "query",
				"text": "Normal"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.PointAtParameter",
				"itemType": "action",
				"text": "PointAtParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.TangentAtParameter",
				"itemType": "action",
				"text": "TangentAtParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.NormalAtParameter",
				"itemType": "action",
				"text": "NormalAtParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.CoordinateSystemAtParameter",
				"itemType": "action",
				"text": "CoordinateSystemAtParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.HorizontalFrameAtParameter",
				"itemType": "action",
				"text": "HorizontalFrameAtParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.PlaneAtParameter",
				"itemType": "action",
				"text": "PlaneAtParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.PointAtSegmentLength",
				"itemType": "action",
				"text": "PointAtSegmentLength"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.PointsAtEqualSegmentLength",
				"itemType": "action",
				"text": "PointsAtEqualSegmentLength"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.PointsAtEqualChordLength",
				"itemType": "action",
				"text": "PointsAtEqualChordLength"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.PointAtChordLength",
				"itemType": "action",
				"text": "PointAtChordLength"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.PointsAtSegmentLengthFromPoint",
				"itemType": "action",
				"text": "PointsAtSegmentLengthFromPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.PointsAtChordLengthFromPoint",
				"itemType": "action",
				"text": "PointsAtChordLengthFromPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.CoordinateSystemAtSegmentLength",
				"itemType": "action",
				"text": "CoordinateSystemAtSegmentLength"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.PlaneAtSegmentLength",
				"itemType": "action",
				"text": "PlaneAtSegmentLength"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.SegmentLengthAtParameter",
				"itemType": "action",
				"text": "SegmentLengthAtParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ParameterAtSegmentLength",
				"itemType": "action",
				"text": "ParameterAtSegmentLength"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ParameterAtChordLength",
				"itemType": "action",
				"text": "ParameterAtChordLength"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.StartParameter",
				"itemType": "action",
				"text": "StartParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.EndParameter",
				"itemType": "action",
				"text": "EndParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.SegmentLengthBetweenParameters",
				"itemType": "action",
				"text": "SegmentLengthBetweenParameters"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ParameterAtPoint",
				"itemType": "action",
				"text": "ParameterAtPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.Reverse",
				"itemType": "action",
				"text": "Reverse"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.Offset",
				"itemType": "action",
				"text": "Offset"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.PullOntoPlane",
				"itemType": "action",
				"text": "PullOntoPlane"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.PullOntoSurface",
				"itemType": "action",
				"text": "PullOntoSurface"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.TrimByStartParameter",
				"itemType": "action",
				"text": "TrimByStartParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.TrimByEndParameter",
				"itemType": "action",
				"text": "TrimByEndParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.TrimByParameter",
				"itemType": "action",
				"text": "TrimByParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.TrimInteriorByParameter",
				"itemType": "action",
				"text": "TrimInteriorByParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.TrimSegmentsByParameter.double1",
				"itemType": "action",
				"text": "TrimSegmentsByParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.TrimSegmentsByParameter.double1-bool",
				"itemType": "action",
				"text": "TrimSegmentsByParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.SplitByParameter.double",
				"itemType": "action",
				"text": "SplitByParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.SplitByParameter.double1",
				"itemType": "action",
				"text": "SplitByParameter"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.SplitByPoints",
				"itemType": "action",
				"text": "SplitByPoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.Join",
				"itemType": "action",
				"text": "Join"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.Extrude.double",
				"itemType": "action",
				"text": "Extrude"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.Extrude.Vector",
				"itemType": "action",
				"text": "Extrude"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.Extrude.Vector-double",
				"itemType": "action",
				"text": "Extrude"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ExtrudeAsSolid.double",
				"itemType": "action",
				"text": "ExtrudeAsSolid"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ExtrudeAsSolid.Vector",
				"itemType": "action",
				"text": "ExtrudeAsSolid"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ExtrudeAsSolid.Vector-double",
				"itemType": "action",
				"text": "ExtrudeAsSolid"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.Extend",
				"itemType": "action",
				"text": "Extend"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ExtendStart",
				"itemType": "action",
				"text": "ExtendStart"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ExtendEnd",
				"itemType": "action",
				"text": "ExtendEnd"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ApproximateWithArcAndLineSegments",
				"itemType": "action",
				"text": "ApproximateWithArcAndLineSegments"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.ToNurbsCurve",
				"itemType": "action",
				"text": "ToNurbsCurve"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.Patch",
				"itemType": "action",
				"text": "Patch"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.Project",
				"itemType": "action",
				"text": "Project"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.SweepAsSurface",
				"itemType": "action",
				"text": "SweepAsSurface"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.SweepAsSolid",
				"itemType": "action",
				"text": "SweepAsSolid"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Curve.Simplify",
				"itemType": "action",
				"text": "Simplify"
			}],
			"iconName": "Curve",
			"itemType": "none",
			"text": "Curve"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Translate.double-double-double",
				"itemType": "action",
				"text": "Translate"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Translate.Vector",
				"itemType": "action",
				"text": "Translate"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Translate.Vector-double",
				"itemType": "action",
				"text": "Translate"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Transform.CoordinateSystem",
				"itemType": "action",
				"text": "Transform"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Transform.CoordinateSystem-CoordinateSystem",
				"itemType": "action",
				"text": "Transform"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Rotate.Point-Vector-double",
				"itemType": "action",
				"text": "Rotate"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Rotate.Plane-double",
				"itemType": "action",
				"text": "Rotate"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Mirror",
				"itemType": "action",
				"text": "Mirror"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Scale.double",
				"itemType": "action",
				"text": "Scale"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Scale.double-double-double",
				"itemType": "action",
				"text": "Scale"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Scale.Plane-double-double-double",
				"itemType": "action",
				"text": "Scale"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Scale.Point-Point-Point",
				"itemType": "action",
				"text": "Scale"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Scale1D",
				"itemType": "action",
				"text": "Scale1D"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Scale2D",
				"itemType": "action",
				"text": "Scale2D"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.DistanceTo",
				"itemType": "action",
				"text": "DistanceTo"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.ClosestPointTo",
				"itemType": "action",
				"text": "ClosestPointTo"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.DoesIntersect",
				"itemType": "action",
				"text": "DoesIntersect"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Intersect",
				"itemType": "action",
				"text": "Intersect"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.IntersectAll",
				"itemType": "action",
				"text": "IntersectAll"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Split",
				"itemType": "action",
				"text": "Split"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Trim",
				"itemType": "action",
				"text": "Trim"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.Explode",
				"itemType": "action",
				"text": "Explode"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.IsAlmostEqualTo",
				"itemType": "action",
				"text": "IsAlmostEqualTo"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.BoundingBox",
				"itemType": "query",
				"text": "BoundingBox"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.ImportFromSAT.var",
				"itemType": "action",
				"text": "ImportFromSAT"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.ImportFromSAT.string",
				"itemType": "action",
				"text": "ImportFromSAT"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.ExportToSAT.Geometry1-string",
				"itemType": "action",
				"text": "ExportToSAT"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.SerializeAsSAB.",
				"itemType": "action",
				"text": "SerializeAsSAB"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.SerializeAsSAB.Geometry1",
				"itemType": "action",
				"text": "SerializeAsSAB"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.DeserializeFromSAB",
				"itemType": "action",
				"text": "DeserializeFromSAB"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Geometry.ContextCoordinateSystem",
				"itemType": "query",
				"text": "ContextCoordinateSystem"
			}],
			"iconName": "Geometry",
			"itemType": "none",
			"text": "Geometry"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.BoundingBox.ByGeometry",
				"itemType": "creation",
				"text": "ByGeometry"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.BoundingBox.ByCorners",
				"itemType": "creation",
				"text": "ByCorners"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.BoundingBox.MinPoint",
				"itemType": "query",
				"text": "MinPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.BoundingBox.MaxPoint",
				"itemType": "query",
				"text": "MaxPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.BoundingBox.Intersection",
				"itemType": "action",
				"text": "Intersection"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.BoundingBox.Intersects",
				"itemType": "action",
				"text": "Intersects"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.BoundingBox.IsEmpty",
				"itemType": "action",
				"text": "IsEmpty"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.BoundingBox.Contains",
				"itemType": "action",
				"text": "Contains"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.BoundingBox.ToCuboid",
				"itemType": "action",
				"text": "ToCuboid"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.BoundingBox.ToPolySurface",
				"itemType": "action",
				"text": "ToPolySurface"
			}],
			"iconName": "BoundingBox",
			"itemType": "none",
			"text": "BoundingBox"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.CoordinateSystem.Identity",
				"itemType": "creation",
				"text": "Identity"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByMatrix",
				"itemType": "creation",
				"text": "ByMatrix"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByOrigin.double-double",
				"itemType": "creation",
				"text": "ByOrigin"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByOrigin.double-double-double",
				"itemType": "creation",
				"text": "ByOrigin"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByOrigin.Point",
				"itemType": "creation",
				"text": "ByOrigin"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByPlane",
				"itemType": "creation",
				"text": "ByPlane"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByOriginVectors.Point-Vector-Vector",
				"itemType": "creation",
				"text": "ByOriginVectors"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.CoordinateSystem.ByOriginVectors.Point-Vector-Vector-Vector",
				"itemType": "creation",
				"text": "ByJoinedSurfaces"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.BySolid",
				"itemType": "creation",
				"text": "BySolid"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.BySweep.Curve-Curve1",
				"itemType": "creation",
				"text": "BySweep"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.BySweep.Curve-Curve",
				"itemType": "creation",
				"text": "BySweep"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.Surfaces",
				"itemType": "action",
				"text": "Surfaces"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.LocateSurfacesByPoint",
				"itemType": "action",
				"text": "LocateSurfacesByPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.LocateSurfacesByLine",
				"itemType": "action",
				"text": "LocateSurfacesByLine"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.UnconnectedBoundaries",
				"itemType": "action",
				"text": "UnconnectedBoundaries"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.ExtractSolids",
				"itemType": "action",
				"text": "ExtractSolids"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.SurfaceCount",
				"itemType": "action",
				"text": "SurfaceCount"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.EdgeCount",
				"itemType": "action",
				"text": "EdgeCount"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.VertexCount",
				"itemType": "action",
				"text": "VertexCount"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.Fillet",
				"itemType": "action",
				"text": "Fillet"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.PolySurface.Chamfer",
				"itemType": "action",
				"text": "Chamfer"
			}],
			"iconName": "PolySurface",
			"itemType": "none",
			"text": "PolySurface"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadius",
				"itemType": "creation",
				"text": "ByCenterPointRadius"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Circle.ByCenterPointRadiusNormal",
				"itemType": "creation",
				"text": "ByCenterPointRadiusNormal"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Circle.ByPlaneRadius",
				"itemType": "creation",
				"text": "ByPlaneRadius"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Circle.ByThreePoints",
				"itemType": "creation",
				"text": "ByThreePoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Circle.ByBestFitThroughPoints",
				"itemType": "creation",
				"text": "ByBestFitThroughPoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Circle.CenterPoint",
				"itemType": "query",
				"text": "CenterPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Circle.Radius",
				"itemType": "query",
				"text": "Radius"
			}],
			"iconName": "Circle",
			"itemType": "none",
			"text": "Circle"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Edge.CurveGeometry",
				"itemType": "query",
				"text": "CurveGeometry"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Edge.AdjacentFaces",
				"itemType": "query",
				"text": "AdjacentFaces"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Edge.StartVertex",
				"itemType": "query",
				"text": "StartVertex"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Edge.EndVertex",
				"itemType": "query",
				"text": "EndVertex"
			}],
			"iconName": "Edge",
			"itemType": "none",
			"text": "Edge"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Vertex.PointGeometry",
				"itemType": "query",
				"text": "PointGeometry"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Vertex.AdjacentEdges",
				"itemType": "query",
				"text": "AdjacentEdges"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Vertex.AdjacentFaces",
				"itemType": "query",
				"text": "AdjacentFaces"
			}],
			"iconName": "Vertex",
			"itemType": "none",
			"text": "Vertex"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cone.ByPointsRadius",
				"itemType": "creation",
				"text": "ByPointsRadius"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cone.ByPointsRadii",
				"itemType": "creation",
				"text": "ByPointsRadii"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cone.ByCoordinateSystemHeightRadius",
				"itemType": "creation",
				"text": "ByCoordinateSystemHeightRadius"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cone.ByCoordinateSystemHeightRadii",
				"itemType": "creation",
				"text": "ByCoordinateSystemHeightRadii"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cone.StartPoint",
				"itemType": "query",
				"text": "StartPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cone.EndPoint",
				"itemType": "query",
				"text": "EndPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cone.RadiusRatio",
				"itemType": "query",
				"text": "RadiusRatio"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cone.StartRadius",
				"itemType": "query",
				"text": "StartRadius"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cone.EndRadius",
				"itemType": "query",
				"text": "EndRadius"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cone.Height",
				"itemType": "query",
				"text": "Height"
			}],
			"iconName": "Cone",
			"itemType": "none",
			"text": "Cone"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Topology.Vertices",
				"itemType": "query",
				"text": "Vertices"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Topology.Edges",
				"itemType": "query",
				"text": "Edges"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Topology.Faces",
				"itemType": "query",
				"text": "Faces"
			}],
			"iconName": "Topology",
			"itemType": "none",
			"text": "Topology"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Face.Edges",
				"itemType": "query",
				"text": "Edges"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Face.Vertices",
				"itemType": "query",
				"text": "Vertices"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Face.SurfaceGeometry",
				"itemType": "action",
				"text": "SurfaceGeometry"
			}],
			"iconName": "Face",
			"itemType": "none",
			"text": "Face"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cylinder.ByRadiusHeight",
				"itemType": "creation",
				"text": "ByRadiusHeight"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cylinder.ByPointsRadius",
				"itemType": "creation",
				"text": "ByPointsRadius"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Cylinder.Radius",
				"itemType": "query",
				"text": "Radius"
			}],
			"iconName": "Cylinder",
			"itemType": "none",
			"text": "Cylinder"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Ellipse.ByOriginRadii",
				"itemType": "creation",
				"text": "ByOriginRadii"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Ellipse.ByOriginVectors",
				"itemType": "creation",
				"text": "ByOriginVectors"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Ellipse.ByCoordinateSystemRadii",
				"itemType": "creation",
				"text": "ByCoordinateSystemRadii"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Ellipse.ByPlaneRadii",
				"itemType": "creation",
				"text": "ByPlaneRadii"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Ellipse.CenterPoint",
				"itemType": "query",
				"text": "CenterPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Ellipse.MajorAxis",
				"itemType": "query",
				"text": "MajorAxis"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Ellipse.MinorAxis",
				"itemType": "query",
				"text": "MinorAxis"
			}],
			"iconName": "Ellipse",
			"itemType": "none",
			"text": "Ellipse"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.EllipseArc.ByPlaneRadiiAngles",
				"itemType": "creation",
				"text": "ByPlaneRadiiAngles"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.EllipseArc.CenterPoint",
				"itemType": "query",
				"text": "CenterPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.EllipseArc.MajorAxis",
				"itemType": "query",
				"text": "MajorAxis"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.EllipseArc.MinorAxis",
				"itemType": "query",
				"text": "MinorAxis"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.EllipseArc.StartAngle",
				"itemType": "query",
				"text": "StartAngle"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.EllipseArc.SweepAngle",
				"itemType": "query",
				"text": "SweepAngle"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.EllipseArc.Plane",
				"itemType": "query",
				"text": "Plane"
			}],
			"iconName": "EllipseArc",
			"itemType": "none",
			"text": "EllipseArc"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Helix.ByAxis",
				"itemType": "creation",
				"text": "ByAxis"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Helix.Angle",
				"itemType": "query",
				"text": "Angle"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Helix.Pitch",
				"itemType": "query",
				"text": "Pitch"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Helix.Radius",
				"itemType": "query",
				"text": "Radius"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Helix.AxisDirection",
				"itemType": "query",
				"text": "AxisDirection"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Helix.AxisPoint",
				"itemType": "query",
				"text": "AxisPoint"
			}],
			"iconName": "Helix",
			"itemType": "none",
			"text": "Helix"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.IndexGroup.ByIndices.int-int-int-int",
				"itemType": "creation",
				"text": "ByIndices"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.IndexGroup.ByIndices.int-int-int",
				"itemType": "creation",
				"text": "ByIndices"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.IndexGroup.Count",
				"itemType": "query",
				"text": "Count"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.IndexGroup.A",
				"itemType": "query",
				"text": "A"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.IndexGroup.B",
				"itemType": "query",
				"text": "B"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.IndexGroup.C",
				"itemType": "query",
				"text": "C"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.IndexGroup.D",
				"itemType": "query",
				"text": "D"
			}],
			"iconName": "IndexGroup",
			"itemType": "none",
			"text": "IndexGroup"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint",
				"itemType": "creation",
				"text": "ByStartPointEndPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Line.ByBestFitThroughPoints",
				"itemType": "creation",
				"text": "ByBestFitThroughPoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Line.ByTangency",
				"itemType": "creation",
				"text": "ByTangency"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Line.ByStartPointDirectionLength",
				"itemType": "creation",
				"text": "ByStartPointDirectionLength"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Line.Direction",
				"itemType": "query",
				"text": "Direction"
			}],
			"iconName": "Line",
			"itemType": "none",
			"text": "Line"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Mesh.ByPointsFaceIndices",
				"itemType": "creation",
				"text": "ByPointsFaceIndices"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Mesh.FaceIndices",
				"itemType": "query",
				"text": "FaceIndices"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Mesh.VertexNormals",
				"itemType": "query",
				"text": "VertexNormals"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Mesh.VertexPositions",
				"itemType": "query",
				"text": "VertexPositions"
			}],
			"iconName": "Mesh",
			"itemType": "none",
			"text": "Mesh"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.ByPoints",
				"itemType": "creation",
				"text": "ByPoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.ByPointsTangents",
				"itemType": "creation",
				"text": "ByPointsTangents"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.ByPointsTangentsKnotsDerivatives",
				"itemType": "creation",
				"text": "ByPointsTangentsKnotsDerivatives"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.ByControlPoints",
				"itemType": "creation",
				"text": "ByControlPoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.ByControlPointsWeightsKnots",
				"itemType": "creation",
				"text": "ByControlPointsWeightsKnots"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.DegreeU",
				"itemType": "query",
				"text": "DegreeU"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.DegreeV",
				"itemType": "query",
				"text": "DegreeV"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.NumControlPointsU",
				"itemType": "query",
				"text": "NumControlPointsU"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.NumControlPointsV",
				"itemType": "query",
				"text": "NumControlPointsV"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.IsPeriodicInU",
				"itemType": "query",
				"text": "IsPeriodicInU"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.IsPeriodicInV",
				"itemType": "query",
				"text": "IsPeriodicInV"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.IsRational",
				"itemType": "query",
				"text": "IsRational"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.ControlPoints",
				"itemType": "action",
				"text": "ControlPoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.Weights",
				"itemType": "action",
				"text": "Weights"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.UKnots",
				"itemType": "action",
				"text": "UKnots"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.NurbsSurface.VKnots",
				"itemType": "action",
				"text": "VKnots"
			}],
			"iconName": "NurbsSurface",
			"itemType": "none",
			"text": "NurbsSurface"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Polygon.ByPoints",
				"itemType": "creation",
				"text": "ByPoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Polygon.RegularPolygon",
				"itemType": "creation",
				"text": "RegularPolygon"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Polygon.Points",
				"itemType": "query",
				"text": "Points"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Polygon.PlaneDeviation",
				"itemType": "query",
				"text": "PlaneDeviation"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Polygon.Corners",
				"itemType": "action",
				"text": "Corners"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Polygon.Center",
				"itemType": "action",
				"text": "Center"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Polygon.SelfIntersections",
				"itemType": "action",
				"text": "SelfIntersections"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Polygon.ContainmentTest",
				"itemType": "action",
				"text": "ContainmentTest"
			}],
			"iconName": "Polygon",
			"itemType": "none",
			"text": "Polygon"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Rectangle.ByCornerPoints.Point1",
				"itemType": "creation",
				"text": "ByCornerPoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Rectangle.ByCornerPoints.Point-Point-Point-Point",
				"itemType": "creation",
				"text": "ByCornerPoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength.double-double",
				"itemType": "creation",
				"text": "ByWidthLength"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength.Plane-double-double",
				"itemType": "creation",
				"text": "ByWidthLength"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Rectangle.ByWidthLength.CoordinateSystem-double-double",
				"itemType": "creation",
				"text": "ByWidthLength"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Rectangle.Width",
				"itemType": "query",
				"text": "Width"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Rectangle.Height",
				"itemType": "query",
				"text": "Height"
			}],
			"iconName": "Rectangle",
			"itemType": "none",
			"text": "Rectangle"
		}, {
			"childItems": [{
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Sphere.ByCenterPointRadius",
				"itemType": "creation",
				"text": "ByCenterPointRadius"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Sphere.ByFourPoints",
				"itemType": "creation",
				"text": "ByFourPoints"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Sphere.ByBestFit",
				"itemType": "creation",
				"text": "ByBestFit"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Sphere.CenterPoint",
				"itemType": "query",
				"text": "CenterPoint"
			}, {
				"childItems": [],
				"iconName": "Autodesk.DesignScript.Geometry.Sphere.Radius",
				"itemType": "query",
				"text": "Radius"
			}],
			"iconName": "Sphere",
			"itemType": "none",
			"text": "Sphere"
		}],
		"iconName": "Geometry",
		"itemType": "category",
		"text": "Geometry"
	}],
	"iconName": null,
	"itemType": null,
	"text": null
}
